touch ft_isalpha.c
touch ft_isdigit.c
touch ft_isalnum.c
touch ft_isascii.c
touch ft_isprint.c
touch ft_strlen.c
touch ft_memset.c
touch ft_bzero.c
touch ft_memcpy.c
touch ft_memmove.c
touch ft_strlcpy.c
touch ft_strlcat.c
touch ft_toupper.c
touch ft_tolower.c
touch ft_strchr.c
touch ft_strrchr.c
touch ft_strncmp.c
touch ft_memchr.c
touch ft_memcmp.c
touch ft_strnstr.c
touch ft_atoi.c
touch ft_calloc.c
touch ft_strdup.c
touch ft_substr.c
touch ft_strjoin.c
touch ft_strtrim.c
touch ft_split.c
touch ft_itoa.c
touch ft_strmapi.c
touch ft_striteri.c
touch ft_puttouch_fd
touch ft_putstr_fd
touch ft_putendl_fd.c
touch ft_putnbr_fd.c
touch ft_lstnew.c
touch ft_lstadd_front.c
touch ft_lstsize.c
touch ft_lstlast.c
touch ft_lstadd_back.c
touch ft_lstdelone.c
touch ft_lstclear.c
touch ft_lstiter.c
touch ft_lstmap.c
